config/routes.rb
Rails.application.routes.draw do
	get 'pizza', to: 'pizzas#show'
	post 'pizzas/new', to: 'pizzas#new'
	post 'pizzas/add_topping', to: 'pizzas#add_topping'
	root to: 'pizzas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pizza_server.rb
class PizzaServer
	include HTTParty
  base_uri 'https://pizzaserver.herokuapp.com'

  # List pizzas
  def pizzas
    response = self.class.get("/pizzas")
    readable_json(response)
  end

  # Create a pizza
  def create_pizza pizza_name, pizza_descripiton
  	query = {"pizza" => {"name" => "#{pizza_name}", "description" => "#{pizza_descripiton}"}}
    response = self.class.post("/pizzas", :query => query)
    readable_json(response)
  end

	# Create a topping
  def create_topping new_topping
  	query = {topping: {name: "#{new_topping}"}}
    response = self.class.post("/toppings", :query => query)
    readable_json(response)
  end

  # List toppings
  def toppings
    response = self.class.get("/toppings")
    readable_json(response)
  end

  # Add a topping to an existing pizza
  def add_topping_to_pizza pizza_id, topping_id
  	query = {topping_id: "#{topping_id}"}
    response = self.class.post("/pizzas/#{pizza_id}/toppings", :query => query)
    readable_json(response)
  end

  def toppings_on_existing_pizza pizza_id
    response = self.class.get("/pizzas/#{pizza_id}/toppings")
    readable_json(response)
  end

  private

	  def readable_json response
	  	JSON.parse(response.body)
	  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
	before_action :pizza_server_new

	def index
		@pizzas = @pizza_server.pizzas
	end

	def show
		@pizza = params
		begin
		  @toppings = @pizza_server.toppings_on_existing_pizza params[:pizza_id]
		rescue => error
			flash[:error] = "We seem to have run into a problem locating those toppings, want to add a new one?"
		  @toppings = nil
		end
	end

	def add_topping
		@pizza = {'pizza_id' => params[:pizza_id].to_i, 'name' => params[:name], 'description' => params[:description]}
		new_topping = create_topping params["topping"]
		@pizza_server.add_topping_to_pizza params[:pizza_id].to_i, new_topping['id']
		@toppings = @pizza_server.toppings_on_existing_pizza params[:pizza_id] #do I need to do this here?
		render :show
	end

	def new
		@pizza_server.create_pizza params[:name], params[:description]
		@pizzas = @pizza_server.pizzas
		render :index
	end

	private

	def pizza_server_new
		@pizza_server = PizzaServer.new
	end

	def create_topping topping
		@pizza_server.create_topping topping
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
  
end

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Pizza! Pizza! Pizza!
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pizza! Pizza!
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/nav'
    - flash.each do |key, value|
      %div{:class => "#{flash_class(key)}"}
        = value
    = yield

app/views/pizzas/index.html.haml
.container
  .list
    %h1 List of Pizzas
    %p.lead
      Click on a pizza to see topping on pizza.
      %br/
      Or create your very own in this form
    = form_tag '/pizzas/new', method: 'post', :class => 'form-inline' do
      .form-group
        = text_field_tag :name,  params[:name], class: 'form-control', placeholder: "Name"
        = text_field_tag :description,  params[:description], class: 'form-control', placeholder: "Description"
      %button.btn.btn-default{:type => "submit"} Create Pizza
    .list-group
    - @pizzas.each do |pizza|
      %a.list-group-item{:href => pizza_path(pizza_id: "#{pizza['id']}", name: "#{pizza['name']}", description: "#{pizza['description']}")}
        = pizza['name'] 
        .pull-right
          = pizza['description']

app/views/pizzas/show.html.haml
.container
  .list
    %h1= @pizza["name"]
    %h4= "Description: #{@pizza['description']}"
    = form_tag '/pizzas/add_topping', method: 'post', :class => 'form-inline' do
      .form-group
        = text_field_tag :topping,params[:topping], class: 'form-control', placeholder: "Topping", autofocus: true
        = hidden_field_tag :pizza_id,  @pizza["pizza_id"]
        = hidden_field_tag :name,  @pizza["name"]
        = hidden_field_tag :description,  @pizza["description"]
      %button.btn.btn-default{:type => "submit"} Add Topping
    - unless @toppings.nil?
      %ul.list-group
      - @toppings.each do |topping|
        %li.list-group-item
          = topping["name"]